Esto, es la evaluación

In [4]:
pip install --upgrade pip setuptools wheel


Defaulting to user installation because normal site-packages is not writeable
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Note: you may need to restart the kernel to use updated packages.


In [6]:
!pip install transformers

Defaulting to user installation because normal site-packages is not writeable
  Using cached transformers-4.47.1-py3-none-any.whl.metadata (44 kB)
  Using cached regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
  Using cached tokenizers-0.21.0-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
  Using cached safetensors-0.4.5.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [5 lines of output]
  💥 maturin failed
    Caused by: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\IÑIGO\\AppData\\Local\\Temp\\pip-modern-metadata-giezata7', '--interpreter', 'C:\\Users\\IÑIGO\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\python.exe']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory C:\Users\IÑIGO\AppData\Local\Temp\pip-modern-metadata-giezata7 --interpreter C:\Users\IÑIGO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe`
  [end of output]
  
  note: This error originates from a subprocess, and is li

In [1]:
import transformers

In [ ]:
ESTA ES LA EVALUACIÓN DEL MODELO EN EUSKERA (MULTILINGÜE)

In [10]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

model_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\Modelos_Perceptron\multi\checkpoint-1944"
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
data_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\DATASETEUSKERA\articulosTest_limpios_multi.csv"

df = pd.read_csv(data_path)  

df = df.dropna(subset=['ORES_Score'])

df['ORES_Score'] = df['ORES_Score'].astype(str)

texts = df['contenido'].tolist()
labels = df['ORES_Score'].tolist()

expected_labels = set(labels)
print("Etiquetas esperadas:", expected_labels)

encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors="pt")

model.eval()
predictions = []

with torch.no_grad():
    outputs = model(encodings["input_ids"], attention_mask=encodings["attention_mask"])
    logits = outputs.logits
    predicted_ids = torch.argmax(logits, dim=1).tolist()

id2label = {0: 'Start', 1: 'Stub', 2: 'C', 3: 'GA', 4: 'FA', 5: 'B'}  # Asegúrate de que coincide con tu modelo
predictions = [id2label[pred] for pred in predicted_ids]

valid_labels = {'Start', 'Stub', 'C', 'GA', 'FA', 'B'}
predictions = [pred if pred in valid_labels else 'unknown' for pred in predictions]

print("\nClassification Report:")
print(classification_report(labels, predictions, labels=list(valid_labels)))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, predictions, labels=list(valid_labels)))



Etiquetas esperadas: {'FA', 'C', 'Stub', 'B', 'GA', 'Start'}

Classification Report:
              precision    recall  f1-score   support

          FA       0.00      0.00      0.00         3
           C       0.23      0.50      0.31       221
        Stub       0.00      0.00      0.00       811
       Start       0.00      0.00      0.00       420
          GA       0.00      0.33      0.00         6
           B       0.00      0.00      0.00        13

    accuracy                           0.08      1474
   macro avg       0.04      0.14      0.05      1474
weighted avg       0.03      0.08      0.05      1474


Confusion Matrix:
[[  0   2   0   0   1   0]
 [  0 110   0   0 111   0]
 [  0  38   0   0 773   0]
 [  0 322   0   0  98   0]
 [  0   4   0   0   2   0]
 [  0   9   0   0   4   0]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [11]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

model_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\Modelos_Perceptron\multi\checkpoint-1944"
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

data_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\DATASETEUSKERA\articulosTest_limpios_multi.csv"

df = pd.read_csv(data_path)  

df = df.dropna(subset=['ORES_Score'])

df['ORES_Score'] = df['ORES_Score'].astype(str)

texts = df['contenido'].tolist()
labels = df['ORES_Score'].tolist()

majority_class = max(set(labels), key=labels.count)
print(f"Clase mayoritaria: {majority_class}")

majority_predictions = [majority_class] * len(labels)

print("\nClasificación usando la clase mayoritaria:")
print("Classification Report:")
print(classification_report(labels, majority_predictions, labels=list(set(labels))))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, majority_predictions, labels=list(set(labels))))

encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors="pt")

model.eval()
predictions = []

with torch.no_grad():
    outputs = model(encodings["input_ids"], attention_mask=encodings["attention_mask"])
    logits = outputs.logits
    predicted_ids = torch.argmax(logits, dim=1).tolist()

id2label = {0: 'Start', 1: 'Stub', 2: 'C', 3: 'GA', 4: 'FA', 5: 'B'}  # Ajusta si es necesario
predictions = [id2label[pred] for pred in predicted_ids]

valid_labels = set(labels)
predictions = [pred if pred in valid_labels else 'unknown' for pred in predictions]

print("\nClasificación usando el modelo:")
print("Classification Report:")
print(classification_report(labels, predictions, labels=list(valid_labels)))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, predictions, labels=list(valid_labels)))


Clase mayoritaria: Stub

Clasificación usando la clase mayoritaria:
Classification Report:
              precision    recall  f1-score   support

          FA       0.00      0.00      0.00         3
           C       0.00      0.00      0.00       221
        Stub       0.55      1.00      0.71       811
           B       0.00      0.00      0.00        13
          GA       0.00      0.00      0.00         6
       Start       0.00      0.00      0.00       420

    accuracy                           0.55      1474
   macro avg       0.09      0.17      0.12      1474
weighted avg       0.30      0.55      0.39      1474


Confusion Matrix:
[[  0   0   3   0   0   0]
 [  0   0 221   0   0   0]
 [  0   0 811   0   0   0]
 [  0   0  13   0   0   0]
 [  0   0   6   0   0   0]
 [  0   0 420   0   0   0]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Clasificación usando el modelo:
Classification Report:
              precision    recall  f1-score   support

          FA       0.00      0.00      0.00         3
           C       0.23      0.50      0.31       221
        Stub       0.00      0.00      0.00       811
           B       0.00      0.00      0.00        13
          GA       0.00      0.33      0.00         6
       Start       0.00      0.00      0.00       420

    accuracy                           0.08      1474
   macro avg       0.04      0.14      0.05      1474
weighted avg       0.03      0.08      0.05      1474


Confusion Matrix:
[[  0   2   0   0   1   0]
 [  0 110   0   0 111   0]
 [  0  38   0   0 773   0]
 [  0   9   0   0   4   0]
 [  0   4   0   0   2   0]
 [  0 322   0   0  98   0]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


LO DE ABAJO ES PARA EL MODELO MONOLINGÜE (EN INGLÉS)

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

model_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\MODELOBERTV2\checkpoint-3200"
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

data_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\TEST\TESTDEFING.csv"

df = pd.read_csv(data_path)  

df = df.dropna(subset=['ORES_Score'])

df['ORES_Score'] = df['ORES_Score'].astype(str)

texts = df['contenido'].tolist()
labels = df['ORES_Score'].tolist()

expected_labels = set(labels)
print("Etiquetas esperadas:", expected_labels)

encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors="pt")

model.eval()
predictions = []

with torch.no_grad():
    outputs = model(encodings["input_ids"], attention_mask=encodings["attention_mask"])
    logits = outputs.logits
    predicted_ids = torch.argmax(logits, dim=1).tolist()


id2label = {0: 'Start', 1: 'Stub', 2: 'C', 3: 'GA', 4: 'FA', 5: 'B'}  
predictions = [id2label[pred] for pred in predicted_ids]

# 6. Filtrar predicciones inválidas
valid_labels = {'Start', 'Stub', 'C', 'GA', 'FA', 'B'}
predictions = [pred if pred in valid_labels else 'unknown' for pred in predictions]

# 7. Calcular métricas
print("\nClassification Report:")
print(classification_report(labels, predictions, labels=list(valid_labels)))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, predictions, labels=list(valid_labels)))


Etiquetas esperadas: {'Stub', 'FA', 'GA', 'B', 'Start', 'C'}

Classification Report:
              precision    recall  f1-score   support

        Stub       0.83      0.01      0.01       811
           B       0.00      0.00      0.00        13
          FA       0.00      0.00      0.00         3
          GA       0.00      0.00      0.00         6
       Start       0.00      0.00      0.00       420
           C       0.37      0.20      0.26       221

    accuracy                           0.03      1474
   macro avg       0.20      0.03      0.05      1474
weighted avg       0.51      0.03      0.05      1474


Confusion Matrix:
[[  5   0   0 802   0   4]
 [  0   0   0   0   0  13]
 [  0   0   0   0   0   3]
 [  0   0   0   0   0   6]
 [  0   0   2 366   0  52]
 [  1   0   0 175   0  45]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
Majority Label

In [2]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# 1. Cargar el modelo y tokenizer desde la ruta especificada
model_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\MODELOBERTV2\checkpoint-3200"
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

# 2. Cargar los datos de evaluación
data_path = r"C:\Users\IÑIGO\Desktop\Universidad\PLN\TEST\TESTDEFING.csv"

df = pd.read_csv(data_path)  # Asegúrate de que contiene columnas 'contenido' y 'ORES_Score'

# Eliminar las filas con valores NaN en 'ORES_Score'
df = df.dropna(subset=['ORES_Score'])

# Asegurar que las etiquetas sean cadenas de texto
df['ORES_Score'] = df['ORES_Score'].astype(str)

# Extraer textos y etiquetas limpias
texts = df['contenido'].tolist()
labels = df['ORES_Score'].tolist()

# 3. Identificar la clase mayoritaria
majority_class = max(set(labels), key=labels.count)
print(f"Clase mayoritaria: {majority_class}")

# 4. Generar predicciones por la clase mayoritaria
majority_predictions = [majority_class] * len(labels)

# 5. Calcular métricas para el clasificador de la clase mayoritaria
print("\nClasificación usando la clase mayoritaria:")
print("Classification Report:")
print(classification_report(labels, majority_predictions, labels=list(set(labels))))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, majority_predictions, labels=list(set(labels))))

# 6. Tokenizar los textos para evaluación
encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors="pt")

# 7. Hacer predicciones con el modelo
model.eval()
predictions = []

with torch.no_grad():
    outputs = model(encodings["input_ids"], attention_mask=encodings["attention_mask"])
    logits = outputs.logits
    predicted_ids = torch.argmax(logits, dim=1).tolist()

# Crear un mapeo entre IDs del modelo y etiquetas esperadas
id2label = {0: 'Start', 1: 'Stub', 2: 'C', 3: 'GA', 4: 'FA', 5: 'B'}  # Ajusta si es necesario
predictions = [id2label[pred] for pred in predicted_ids]

# Asegurar que las predicciones estén dentro de las etiquetas válidas
valid_labels = set(labels)
predictions = [pred if pred in valid_labels else 'unknown' for pred in predictions]

# 8. Calcular métricas para el modelo
print("\nClasificación usando el modelo:")
print("Classification Report:")
print(classification_report(labels, predictions, labels=list(valid_labels)))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, predictions, labels=list(valid_labels)))

Clase mayoritaria: Stub

Clasificación usando la clase mayoritaria:
Classification Report:
              precision    recall  f1-score   support

        Stub       0.55      1.00      0.71       811
          FA       0.00      0.00      0.00         3
          GA       0.00      0.00      0.00         6
           B       0.00      0.00      0.00        13
       Start       0.00      0.00      0.00       420
           C       0.00      0.00      0.00       221

    accuracy                           0.55      1474
   macro avg       0.09      0.17      0.12      1474
weighted avg       0.30      0.55      0.39      1474


Confusion Matrix:
[[811   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [  6   0   0   0   0   0]
 [ 13   0   0   0   0   0]
 [420   0   0   0   0   0]
 [221   0   0   0   0   0]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Clasificación usando el modelo:
Classification Report:
              precision    recall  f1-score   support

        Stub       0.83      0.01      0.01       811
          FA       0.00      0.00      0.00         3
          GA       0.00      0.00      0.00         6
           B       0.00      0.00      0.00        13
       Start       0.00      0.00      0.00       420
           C       0.37      0.20      0.26       221

    accuracy                           0.03      1474
   macro avg       0.20      0.03      0.05      1474
weighted avg       0.51      0.03      0.05      1474


Confusion Matrix:
[[  5   0 802   0   0   4]
 [  0   0   0   0   0   3]
 [  0   0   0   0   0   6]
 [  0   0   0   0   0  13]
 [  0   2 366   0   0  52]
 [  1   0 175   0   0  45]]


C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\IÑIGO\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
